# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- Threaded

pool:
  vmImage: 'windows-latest'

steps:
- script: |
    pip install pytz
  displayName: 'Installing Python3 build environment'

- script: |
    cd BuildSystem
    doBuild.bat version
  displayName: 'Build third-party libraries'
