# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    sudo apt-get update
    sudo apt -y install g++ gfortran cmake unzip p7zip-full
  displayName: 'Installing C++ build environment'

- script: |
    sudo apt -y install python3 python3-pip
    sudo pip3 install pytz
  displayName: 'Installing Python3 build environment'

- script: |
    cd BuildSystem
    ./doBuild.sh thirdparty parser
  displayName: 'Build third-party libraries'

- script: |
    cd BuildSystem
    ./doBuild.shdebug
  displayName: 'Build Debug stand-alone binary'

- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
